### PR TITLE
Add typescript declarations

### LINKED ISSUE #28: No declaration file for TypeScript support
As the title says, TypeScript throws an error since there is no declaration file for the lib when implicit any is off.

### PR DESCRIPTION
**Pull request by ChuckBorris33**
Closes #28

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Would you mind creating a new release with these changes? Thank you!

**Comment by tobias-kuendig** [comment]
Anything we can do to help you get a new release out that includes the typescript definitions, @y-nk?

**Comment by weihao** [comment]
> Would you mind creating a new release with these changes? Thank you!

@y-nk ^

**Comment by tobias-kuendig** [comment]
For anyone waiting for the release, here is a workaround that uses the current master branch and builds the package using a postinstall script. Just add the following to your `package.json`:

```json
{
    "scripts": {
        "postinstall": "cd ./node_modules/vue-fragment && yarn"
    },
    "dependencies": {
        "vue-fragment": "y-nk/vue-fragment#master",
    }
}
```

You can use `npm install` instead of `yarn` in the `postinstall` script.

**Pull request merged**
